name: Cloudflare Pages Build Logs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Cloudflare Pages build logs for PR branch
        id: fetch_logs
        run: |
          PROJECT_NAME=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PR_BRANCH=${{ github.head_ref }}

          # API call to get the deployments for the PR branch
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X GET \
            "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects/$PROJECT_NAME/deployments" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json")

          # Check if the API call was successful (HTTP 2xx status code)
          if [ "$RESPONSE" -ge 200 ] && [ "$RESPONSE" -lt 300 ]; then
            echo "Cloudflare API request succeeded."
            
            # Filter deployments for the current PR branch
            DEPLOYMENTS=$(jq -c --arg branch "$PR_BRANCH" '.result[] | select(.deployment_trigger.metadata.branch == $branch)' response.json)
            
            if [ -z "$DEPLOYMENTS" ]; then
              BUILD_LOGS="No deployments found for branch: $PR_BRANCH."
            else
              BUILD_LOGS=""
              while IFS= read -r deployment; do
                # Extract the deployment ID to fetch logs
                DEPLOYMENT_ID=$(echo "$deployment" | jq -r '.id')
                
                # Fetching logs using the deployment ID
                LOGS_RESPONSE=$(curl -s -o logs.json -w "%{http_code}" -X GET \
                  "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects/$PROJECT_NAME/deployments/$DEPLOYMENT_ID/logs" \
                  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN")
                
                # Check if logs API call was successful
                if [ "$LOGS_RESPONSE" -ge 200 ] && [ "$LOGS_RESPONSE" -lt 300 ]; then
                  LOGS=$(cat logs.json | jq -r '.result | .[] | .message')
                  BUILD_LOGS+="\n\`\`\`\n$LOGS\n\`\`\`"
                else
                  BUILD_LOGS+="\nFailed to fetch logs for deployment: $DEPLOYMENT_ID"
                fi
              done <<< "$DEPLOYMENTS"
            fi
            echo "::set-output name=logs::$BUILD_LOGS"
          else
            echo "Cloudflare API request failed with status code: $RESPONSE"
            echo "Response:"
            cat response.json
            exit 1  # Explicitly fail the job
          fi

      - name: Post build logs to PR
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const buildLogs = `${{ steps.fetch_logs.outputs.logs }}`;
            const commentBody = `Cloudflare Pages build logs for branch **${{ github.head_ref }}**:\n\n${buildLogs}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
