name: Fetch Deployment Logs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  fetch-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        id: setenv
        run: |
          echo "PROJECT_NAME=${{ secrets.CLOUDFLARE_PROJECT_NAME }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
          echo "ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "PR_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Poll for Cloudflare Pages Build and Fetch Logs
        uses: JDeepD/cloudflare-build-log@0.1.1

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: <!-- CLOUDFLARE_PAGES_BUILD_LOGS -->

      - name: Update or create comment
        if: success()
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            <!-- CLOUDFLARE_PAGES_BUILD_LOGS -->
            ## Cloudflare Pages Build Logs

            **Branch:** ${{ github.head_ref }}
            **Commit:** ${{ github.sha }}
            **Build Time:** ${{ env.BUILD_TIME }}

            <details>
            <summary>Click to expand build logs</summary>

            ${{ env.logs }}

            </details>
          edit-mode: replace
      - name: Post build status
        if: always()
        run: |
          echo "Build status: ${{ job.status }}"
